"""
SQLAlchemy ORM model for mitosis candidates (SPEC-06 §5.6, contract mitosis_v6).

One row per persisted candidate: model candidates the decision kept and figures a pathologist
added. ``counted`` is generated by the database from the decision, the tumour gate and the
pathologist's label, so no code path derives it differently.
"""
from datetime import datetime, timezone
from sqlalchemy import Boolean, Column, Computed, String, Text, Float, DateTime, ForeignKey, JSON, false
from sqlalchemy.dialects.postgresql import JSONB

from app.core.db import Base
from app.models.base import GUID

JSONType = JSON().with_variant(JSONB, "postgresql")

# A pathologist's label decides; otherwise a model 'mitosis' counts when it is in tumour. in_tumor is
# NULL only while the tumour-cell gate is off (mitosis.tumor_gate), and then the candidate is eligible.
COUNTED_SQL = "COALESCE(review_label = 'mitosis', final_decision = 'mitosis' AND COALESCE(in_tumor, TRUE))"


class Detection(Base):
    __tablename__ = "detections"
    # counted is read back with a SELECT when accessed, not with INSERT ... RETURNING: batched RETURNING
    # cannot match rows by the GUID key on SQLite.
    __mapper_args__ = {"eager_defaults": False}

    id = Column(String, primary_key=True) # e.g. m_0001
    case_id = Column(GUID, ForeignKey("cases.id", ondelete="CASCADE"), primary_key=True, index=True)
    hotspot_id = Column(String, nullable=True)
    centroid_um = Column(JSONType, nullable=False) # [x, y] in base micrometers
    p_a = Column(Float, nullable=True) # detector probability as returned (null for pathologist-added)
    p_b = Column(Float, nullable=True) # classifier probability (no classifier in this iteration)
    vlm = Column(JSONType, nullable=True) # the referee's full VlmVerdict, or null
    rule_override = Column(Boolean, nullable=False, default=False, server_default=false()) # post-rule downgraded the VLM verdict
    in_tumor = Column(Boolean, nullable=True) # tumour-cell gate; null while the gate is off
    final_decision = Column(String, nullable=False) # mitosis | not_mitosis | equivocal
    decision_path = Column(String, nullable=False) # A | AB | ABC | human
    review_label = Column(String, nullable=True) # pathologist: mitosis | not_mitosis
    record_ids = Column(JSONType, nullable=True) # DecisionRecord ids of the decision chain
    description = Column(JSONType, nullable=True) # MitosisDescription (morphology only, never a decision), or null
    description_status = Column(Text, nullable=False, default="not_requested", server_default="not_requested") # ok | unavailable | not_requested
    counted = Column(Boolean, Computed(COUNTED_SQL))
    created_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))
