"""The mitosis_v6 contract on the backend (docs/contracts/mitosis_v6.md; SPEC-06 §5.6, AC10; WP-7.6a).

- ``GET /api/v1/stages/mitosis/{case_id}`` validates against a strict Pydantic mirror of the contract's
  TypeScript types, and so does the frontend mock fixture built from the contract's example.
- ``detections.counted`` (generated by the database) equals ``pipeline.scoring.is_counted`` everywhere.
- Migration 0016 maps v5 rows deterministically.
- The score thresholds are compared in ``pipeline/scoring.py`` only (AC10 grep test).
"""
import itertools
import re
import uuid
from pathlib import Path
from typing import Literal, Optional

import pytest
from alembic import command
from fastapi.testclient import TestClient
from pydantic import BaseModel, ConfigDict
from sqlalchemy import create_engine, select, text
from sqlalchemy.orm import sessionmaker
from sqlalchemy.pool import StaticPool

from app.core.db import Base, get_db
from app.core.migrations import alembic_config
from app.main import app
from app.models import Case, Detection, Hotspot, HpfSite, Slide, StageExecution
from pipeline.scoring import is_counted

REPO = Path(__file__).resolve().parents[2]
BACKEND = REPO / "backend"


class Strict(BaseModel):
    model_config = ConfigDict(extra="forbid", strict=True)


class Criteria(Strict):
    membrane_absent: bool
    condensed_chromosome_projections: bool
    phase: Literal["prometaphase", "metaphase", "anaphase", "telophase", "atypical", "none"]
    neoplastic_cell: bool


class VlmVerdict(Strict):
    verdict: Literal["MITOTIC_FIGURE", "NOT_MITOTIC_FIGURE", "EQUIVOCAL"]
    criteria: Criteria
    mimic: Literal["none", "apoptotic_body", "pyknotic_nucleus", "hyperchromatic_interphase", "lymphocyte",
                   "prophase", "crush", "other"]
    rationale: str
    rule_override: bool


Number = float | int


class MitosisDescription(Strict):
    chromatin: Literal["condensed_clumps", "band_or_plate", "two_separated_masses", "fine_granular", "smooth_dense",
                       "beaded_fragments", "not_assessable"]
    nuclear_membrane: Literal["not_visible", "partly_visible", "intact", "not_assessable"]
    outline: Literal["hairy_projections", "smooth", "not_assessable"]
    cytoplasm: Literal["clear_halo", "eosinophilic", "none_visible", "not_assessable"]
    relative_size: Literal["larger", "similar", "smaller", "not_assessable"]
    setting: Literal["tumour_cells", "stroma", "inflammatory", "necrosis", "lumen", "not_assessable"]
    summary: str


class Candidate(Strict):
    id: str
    hotspot_id: Optional[str]
    centroid_um: tuple[Number, Number]
    p_a: Optional[Number]
    p_b: Optional[Number]
    vlm: Optional[VlmVerdict]
    in_tumor: Optional[bool]  # null only in an eval tumour-gate ablation run
    final_decision: Literal["mitosis", "not_mitosis", "equivocal"]
    decision_path: Literal["A", "AB", "ABC", "human"]
    review_label: Optional[Literal["mitosis", "not_mitosis"]]
    counted: bool
    crop_url: str
    context_url: str
    # WP-6.5: the fixture gains these in WP-7.10; the API must always send them (asserted below).
    hpf_seq: Optional[int] = None
    # WP-7.9: morphology description, never a decision.
    description: Optional[MitosisDescription]
    description_status: Literal["ok", "unavailable", "not_requested"]


class Hpf(Strict):
    seq: int
    center_um: tuple[Number, Number]
    radius_um: Number
    count: int
    tissue_coverage: Number
    tumor_fraction: Number
    hotspot_id: Optional[str] = None
    frame_um: Optional[list[tuple[Number, Number]]] = None


class MitosisSummary(Strict):
    count_total: int
    n_hpf: int
    area_mm2: Number
    per_mm2: Number
    mitotic_score: Optional[Literal[1, 2, 3]]
    n_equivocal: int
    flags: list[Literal["hpf_count_lt_10"]]
    hpf_target: Optional[int] = None


class SlideGeom(Strict):
    width_px: int
    height_px: int
    mpp_x: Number
    mpp_y: Number


class Provenance(Strict):
    stage: str
    model_versions: dict[str, str]
    config_hash: str
    run_mode: Literal["clinical", "eval", "shadow"]


class MitosisStageV6(Strict):
    case_id: str
    stage_execution_id: str
    status: Literal["queued", "running", "awaiting_review", "confirmed", "failed"]
    slide: SlideGeom
    candidates: list[Candidate]
    hpfs: list[Hpf]
    summary: MitosisSummary
    provenance: Provenance


@pytest.fixture
def session_factory():
    engine = create_engine("sqlite:///:memory:", connect_args={"check_same_thread": False}, poolclass=StaticPool)
    Base.metadata.create_all(bind=engine)
    factory = sessionmaker(bind=engine, autoflush=False)

    def override():
        db = factory()
        try:
            yield db
        finally:
            db.close()

    app.dependency_overrides[get_db] = override
    yield factory
    app.dependency_overrides.pop(get_db, None)
    engine.dispose()


def test_the_mock_fixture_matches_the_contract():
    # JSON mode: arrays are the TypeScript tuples.
    MitosisStageV6.model_validate_json((REPO / "frontend/lib/mock/mitosis.json").read_text(encoding="utf-8"))


def seed_case(db, *, n_hpf: int):
    case_id = uuid.uuid4()
    db.add(Case(id=case_id, created_by="contract_test"))
    db.add(Slide(id=uuid.uuid4(), case_id=case_id, gcs_uri_original="gs://raw/s.svs", mpp_x=0.25, mpp_y=0.25,
                 width_px=40000, height_px=40000))
    db.add(StageExecution(id=uuid.uuid4(), case_id=case_id, stage="mitosis", attempt=1, status="awaiting_review",
                          model_versions={"kongnet_det_midog_1": "v2"}, config_hash="c" * 64))
    db.flush()
    exec_id = db.scalars(select(StageExecution.id).where(StageExecution.case_id == case_id)).one()
    for seq in range(1, n_hpf + 1):
        centre = [1000.0 * seq, 1000.0]
        db.add(HpfSite(case_id=case_id, seq=seq, center_um=centre, radius_um=250.0,
                       mitotic_count=0, tissue_coverage=0.95, tumor_fraction=0.8))
        db.add(Hotspot(id=f"hs_{seq:02d}", case_id=case_id, stage_execution_id=exec_id, center_um=centre, hpf_diameter_um=500.0,
                       window_um=600.0, rank=seq, source="model", excluded=False,
                       polygon_um=[[centre[0] - 300, 700.0], [centre[0] + 300, 700.0], [centre[0] + 300, 1300.0],
                                   [centre[0] - 300, 1300.0], [centre[0] - 300, 700.0]]))
    vlm = {"verdict": "EQUIVOCAL", "criteria": {"membrane_absent": True, "condensed_chromosome_projections": False,
                                               "phase": "none", "neoplastic_cell": True},
           "mimic": "pyknotic_nucleus", "rationale": "dense round body", "rule_override": False}
    db.add_all([
        Detection(id="m_0001", case_id=case_id, hotspot_id="hs_01", centroid_um=[1000.0, 1000.0], p_a=0.91,
                  final_decision="mitosis", decision_path="A", record_ids=["r1"]),
        Detection(id="m_0002", case_id=case_id, hotspot_id="hs_01", centroid_um=[1100.0, 1000.0], p_a=0.81, vlm=vlm,
                  final_decision="equivocal", decision_path="A", record_ids=["r2", "r3"]),
        Detection(id="m_user_0a1b2c3d", case_id=case_id, centroid_um=[2000.0, 1000.0], p_a=None,
                  final_decision="mitosis", decision_path="human", review_label="mitosis"),
    ])
    db.commit()
    return str(case_id)


@pytest.mark.parametrize("n_hpf", [10, 3, 0])
def test_get_validates_against_the_contract(session_factory, n_hpf):
    db = session_factory()
    case_id = seed_case(db, n_hpf=n_hpf)
    db.close()
    res = TestClient(app).get(f"/api/v1/stages/mitosis/{case_id}", headers={"X-Test-Role": "pathologist"})
    assert res.status_code == 200, res.text
    stage = MitosisStageV6.model_validate_json(res.text)
    assert stage.summary.hpf_target == 10 and all(c.hpf_seq is None or c.hpf_seq >= 1 for c in stage.candidates)
    assert [h.hotspot_id for h in stage.hpfs] == [f"hs_{seq:02d}" for seq in range(1, n_hpf + 1)]
    assert all(h.frame_um is not None and len(h.frame_um) == 5 for h in stage.hpfs)
    if n_hpf == 0:
        assert stage.summary.mitotic_score is None and stage.summary.n_hpf == 0 and stage.summary.flags == ["hpf_count_lt_10"]
    elif n_hpf == 10:
        assert stage.summary.flags == [] and stage.summary.count_total == 2 and stage.summary.n_equivocal == 1


def test_counted_column_equals_the_python_mirror_for_every_combination(session_factory):
    db = session_factory()
    case_id = uuid.uuid4()
    db.add(Case(id=case_id, created_by="contract_test"))
    combos = list(itertools.product([None, "mitosis", "not_mitosis"], ["mitosis", "not_mitosis", "equivocal"], [None, True, False]))
    for i, (review_label, final_decision, in_tumor) in enumerate(combos):
        db.add(Detection(id=f"m_{i:04d}", case_id=case_id, centroid_um=[float(i), 0.0], p_a=0.9, final_decision=final_decision,
                         decision_path="A", review_label=review_label, in_tumor=in_tumor))
    db.commit()
    for i, combo in enumerate(combos):
        assert bool(db.get(Detection, (f"m_{i:04d}", case_id)).counted) is is_counted(*combo), combo
    db.close()


# -- migration 0016 ------------------------------------------------------------------------------------------------------------------

def run(engine, fn, *args):
    with engine.begin() as conn:
        cfg = alembic_config()
        cfg.attributes["connection"] = conn
        fn(cfg, *args)


V5_ROWS = [
    # id, det_conf, label, label_source -> p_a, final_decision, decision_path, review_label
    ("m_0001", 0.9, "mitosis", "detector:kongnet_det_midog_1", 0.9, "mitosis", "A", None),
    ("m_0002", 0.8, "not_mitosis", "referee:gemini_referee", 0.8, "not_mitosis", "A", None),
    ("m_0003", 0.7, "unreviewed", "referee_unavailable", 0.7, "equivocal", "A", None),
    ("m_0004", 0.6, "not_mitosis", "pathologist", 0.6, "equivocal", "A", "not_mitosis"),
    ("m_0005", 0.6, "not_mitosis", "pathologist_bulk", 0.6, "equivocal", "A", "not_mitosis"),
    ("m_0006", 0.6, "unreviewed", "pathologist", 0.6, "equivocal", "A", None),
    ("m_user_1a2b3c4d", 1.0, "mitosis", "pathologist", None, "mitosis", "human", "mitosis"),
    ("m_0007", None, "mitosis", "pathologist_manual_added", None, "mitosis", "human", "mitosis"),
]


def test_0016_maps_v5_rows_and_drops_the_v5_columns(tmp_path):
    engine = create_engine(f"sqlite:///{tmp_path / 'oncogemma.db'}")
    run(engine, command.upgrade, "0015_hotspot_v6_fields")
    case_id = str(uuid.uuid4())
    with engine.begin() as conn:
        conn.execute(text("INSERT INTO cases (id, created_by, status, created_at) VALUES (:id, 'v5', 'open', CURRENT_TIMESTAMP)"), {"id": case_id})
        for row in V5_ROWS:
            conn.execute(text(
                "INSERT INTO detections (id, case_id, centroid_um, det_conf, label, label_source, medgemma_verdict) "
                "VALUES (:id, :case_id, '[1.0, 2.0]', :det_conf, :label, :source, 'CONFIRMED')"
            ), {"id": row[0], "case_id": case_id, "det_conf": row[1], "label": row[2], "source": row[3]})
    run(engine, command.upgrade, "0016_detections_v6")

    with engine.connect() as conn:
        got = {r.id: r for r in conn.execute(text(
            "SELECT id, p_a, final_decision, decision_path, review_label, vlm, in_tumor, rule_override, counted FROM detections"
        ))}
        columns = {c[1] for c in conn.execute(text("PRAGMA table_xinfo(detections)"))}
    for rid, _, _, _, p_a, final_decision, decision_path, review_label in V5_ROWS:
        r = got[rid]
        assert (r.p_a, r.final_decision, r.decision_path, r.review_label) == (p_a, final_decision, decision_path, review_label), rid
        assert r.vlm is None and r.in_tumor is None and not r.rule_override
        assert bool(r.counted) is is_counted(review_label, final_decision, None)
    assert not columns & {"det_conf", "ver_conf", "label", "label_source", "medgemma_verdict", "medgemma_rationale",
                          "medgemma_confidence", "crop_uri", "crop_orig_uri"}

    run(engine, command.downgrade, "0015_hotspot_v6_fields")
    with engine.connect() as conn:
        back = {r.id: r for r in conn.execute(text("SELECT id, det_conf, label, label_source FROM detections"))}
    assert (back["m_0001"].label, back["m_0001"].label_source) == ("mitosis", "model")
    assert (back["m_0004"].label, back["m_0004"].label_source) == ("not_mitosis", "pathologist")
    assert back["m_0003"].label == "unreviewed"
    engine.dispose()


# -- AC10: one scoring implementation ------------------------------------------------------------------------------------------------

def test_score_thresholds_are_compared_only_in_pipeline_scoring():
    """SPEC-06 AC10: no backend file other than pipeline/scoring.py reads the mitotic score thresholds
    (pipeline_config.py declares them; tests are excluded)."""
    allowed = {BACKEND / "pipeline" / "scoring.py", BACKEND / "app" / "core" / "pipeline_config.py"}
    pattern = re.compile(r"\.score[23]_min\b")  # the mitotic thresholds, not the tubule *_min_percent
    offenders = [
        str(path.relative_to(REPO)) for path in BACKEND.rglob("*.py")
        if "tests" not in path.relative_to(BACKEND).parts and path not in allowed
        and pattern.search(path.read_text(encoding="utf-8"))
    ]
    assert offenders == []


def test_the_v5_review_gate_setting_is_gone():
    """The equivocal confirm gate replaces review.gate_min_conf (WP-7.6a)."""
    assert "gate_min_conf" not in (REPO / "configs" / "mitosis.yaml").read_text(encoding="utf-8")
    assert not [p for p in BACKEND.rglob("*.py") if "tests" not in p.parts and "gate_min_conf" in p.read_text(encoding="utf-8")]
