"""
Stage 4 counting and the Nottingham mitotic score: the single implementation (SPEC-06 §5.8, AC10).

A candidate counts when it is ``counted`` (generated by the database from the decision, the tumour
gate and the pathologist's label; ``is_counted`` mirrors it for candidates not yet persisted) and
lies inside an HPF disk. The density is per mm² of the placed HPFs, and the score thresholds come
from the injected ``MitosisScoringConfig`` (configs/mitosis.yaml, SPEC-01 §3.8). Every recompute,
in the worker, the API and grading, goes through this module.
"""
import math
from typing import List, Dict, Any, Tuple, Optional

from app.core.pipeline_config import MitosisScoringConfig

# Summary flag when fewer than the configured number of HPFs fit (SPEC-06 §5.8).
HPF_COUNT_LT_10 = "hpf_count_lt_10"


def is_counted(review_label: Optional[str], final_decision: str, in_tumor: Optional[bool]) -> bool:
    """``detections.counted`` for a candidate that is not persisted yet (app/models/detection.py COUNTED_SQL)."""
    if review_label is not None:
        return review_label == "mitosis"
    return final_decision == "mitosis" and (True if in_tumor is None else in_tumor)


def _inside(cand: Dict[str, Any], hpf: Dict[str, Any]) -> bool:
    cx, cy = hpf["center_um"]
    r = float(hpf["radius_um"])
    x, y = cand["centroid_um"]
    return (x - cx) ** 2 + (y - cy) ** 2 <= r * r


def calculate_hpf_mitosis_counts(
    candidates: List[Dict[str, Any]],
    hpfs: List[Dict[str, Any]]
) -> Tuple[List[Dict[str, Any]], int]:
    """
    Sets each HPF's ``count`` to the counted candidates inside its disk and returns the HPFs with
    the number of distinct counted candidates inside any HPF (a figure in two disks counts once).
    """
    updated_hpfs = []
    mitoses_in_any_hpf = set()

    for hpf in hpfs:
        hpf_copy = dict(hpf)
        inside = [cand["id"] for cand in candidates if cand["counted"] and _inside(cand, hpf_copy)]
        hpf_copy["count"] = len(inside)
        mitoses_in_any_hpf.update(inside)
        updated_hpfs.append(hpf_copy)

    return updated_hpfs, len(mitoses_in_any_hpf)


def compute_nottingham_mitotic_score(
    count_total: int,
    n_hpf: int,
    radius_um: Optional[float],
    scoring: MitosisScoringConfig,
    hpfs: Optional[List[Dict[str, Any]]] = None
) -> Dict[str, Any]:
    """
    Computes Nottingham Mitotic Score based on standardized mm² area normalization.

    ``scoring.thresholds`` give the mitoses/mm² at which the score becomes 2 and 3
    (Elston-Ellis: 3.65 and 7.30 per mm², classic 10 and 20 per 2.74 mm²).
    With ``hpfs`` the area is the sum of their own radii; otherwise ``n_hpf`` fields of ``radius_um``.
    With no HPF there is no area, so there is no score (``mitotic_score`` is None).
    """
    score2_min = scoring.thresholds.score2_min
    score3_min = scoring.thresholds.score3_min

    # Calculate actual cumulative HPF inspection area summing per-HPF radius (#764)
    if hpfs:
        n_fields = len(hpfs)
        area_mm2 = sum(math.pi * ((float(h["radius_um"]) / 1000.0) ** 2) for h in hpfs)
    elif n_hpf > 0:
        n_fields = n_hpf
        single_hpf_area_mm2 = math.pi * ((radius_um / 1000.0) ** 2)
        area_mm2 = float(n_fields * single_hpf_area_mm2)
    else:
        n_fields, area_mm2 = 0, 0.0

    if n_fields <= 0 or area_mm2 <= 0.0:
        return {
            "count_total": int(count_total),
            "n_hpf": 0,
            "area_mm2": 0.0,
            "per_mm2": 0.0,
            "mitoses_per_mm2": 0.0,
            "classic_per_10hpf": 0.0,
            "mitotic_score": None,
            "score": None
        }

    density = float(count_total) / area_mm2
    classic_per_10hpf = density * scoring.classic_area_mm2

    # Determine score
    if density >= score3_min:
        mitotic_score = 3
    elif density >= score2_min:
        mitotic_score = 2
    else:
        mitotic_score = 1

    return {
        "count_total": int(count_total),
        "n_hpf": int(n_fields),
        "area_mm2": round(area_mm2, 3),
        "per_mm2": round(density, 2),
        "mitoses_per_mm2": round(density, 2),
        "classic_per_10hpf": round(classic_per_10hpf, 1),
        "mitotic_score": mitotic_score,
        "score": mitotic_score
    }


def equivocal_unreviewed_in_hpfs(candidates: List[Dict[str, Any]], hpfs: List[Dict[str, Any]]) -> List[str]:
    """Ids of ``equivocal`` candidates inside an HPF that no pathologist has labelled (they block confirmation)."""
    return [
        c["id"] for c in candidates
        if c["final_decision"] == "equivocal" and c["review_label"] is None and any(_inside(c, h) for h in hpfs)
    ]


def summarize_stage4(
    candidates: List[Dict[str, Any]],
    hpfs: List[Dict[str, Any]],
    *,
    scoring: MitosisScoringConfig,
    hpf_count: int,
) -> Tuple[List[Dict[str, Any]], Dict[str, Any]]:
    """The HPFs with their counts and the contract's ``MitosisSummary`` (docs/contracts/mitosis_v6.md).

    ``candidates`` carry ``id``, ``centroid_um``, ``counted``, ``final_decision`` and ``review_label``;
    ``hpf_count`` is the number of HPFs the score is meant to examine (``specimen_profiles.<type>.hotspots.k_max``).
    """
    counted_hpfs, total = calculate_hpf_mitosis_counts(candidates, hpfs)
    score = compute_nottingham_mitotic_score(count_total=total, n_hpf=len(hpfs), radius_um=None, scoring=scoring, hpfs=hpfs)
    summary = {
        "count_total": score["count_total"],
        "n_hpf": score["n_hpf"],
        "area_mm2": score["area_mm2"],
        "per_mm2": score["per_mm2"],
        "mitotic_score": score["mitotic_score"],
        "n_equivocal": len(equivocal_unreviewed_in_hpfs(candidates, hpfs)),
        "hpf_target": hpf_count,
        "flags": [HPF_COUNT_LT_10] if len(hpfs) < hpf_count else [],
    }
    return counted_hpfs, summary
