"""v5 baseline: the schema v5 built with create_all, autogenerated from the models.

A database built by v5 is stamped at this revision instead of upgraded
(see app.core.migrations.upgrade_to_head).

Revision ID: 0001_v5_baseline
Revises: 
Create Date: 2026-09-28 16:44:39.461743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.models.base import GUID
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001_v5_baseline'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table('audit_events',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.String(), nullable=True),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cases',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', GUID(), nullable=False),
    sa.Column('hotspot_id', sa.String(), nullable=True),
    sa.Column('centroid_um', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('det_conf', sa.Float(), nullable=True),
    sa.Column('ver_conf', sa.Float(), nullable=True),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('label_source', sa.String(), nullable=False),
    sa.Column('medgemma_verdict', sa.String(), nullable=True),
    sa.Column('medgemma_rationale', sa.Text(), nullable=True),
    sa.Column('medgemma_confidence', sa.String(), nullable=True),
    sa.Column('crop_uri', sa.Text(), nullable=True),
    sa.Column('crop_orig_uri', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'case_id')
    )
    op.create_index('ix_detections_case_id', 'detections', ['case_id'], unique=False)

    op.create_table('gradings',
    sa.Column('case_id', GUID(), nullable=False),
    sa.Column('tubule_percent', sa.Float(), nullable=True),
    sa.Column('tubule_score', sa.Integer(), nullable=True),
    sa.Column('pleo_score', sa.Integer(), nullable=True),
    sa.Column('mitotic_score', sa.Integer(), nullable=True),
    sa.Column('nottingham_sum', sa.Integer(), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('histologic_type', sa.String(), nullable=False),
    sa.Column('type_confirmed_by', sa.String(), nullable=False),
    sa.Column('machine', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('overrides', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('grade = CASE WHEN tubule_score + pleo_score + mitotic_score <= 5 THEN 1 WHEN tubule_score + pleo_score + mitotic_score <= 7 THEN 2 ELSE 3 END', name='check_nottingham_grade_calc'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_table('hpf_sites',
    sa.Column('case_id', GUID(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('center_um', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('radius_um', sa.Float(), nullable=False),
    sa.Column('mitotic_count', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('image_patch_uri', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('case_id', 'seq')
    )
    op.create_index('ix_hpf_sites_case_id', 'hpf_sites', ['case_id'], unique=False)

    op.create_table('reports',
    sa.Column('case_id', GUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('specimen_type', sa.String(), nullable=False),
    sa.Column('procedure', sa.String(), nullable=False),
    sa.Column('laterality', sa.String(), nullable=False),
    sa.Column('tumor_site', sa.String(), nullable=False),
    sa.Column('histologic_type', sa.String(), nullable=False),
    sa.Column('tumor_size_mm', sa.Float(), nullable=True),
    sa.Column('lvi_status', sa.String(), nullable=False),
    sa.Column('dcis_present', sa.Boolean(), nullable=False),
    sa.Column('margins', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('lymph_nodes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('biomarkers', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('staging', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('narrative', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('visual_evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('pdf_path', sa.String(), nullable=True),
    sa.Column('pdf_sha256', sa.String(), nullable=True),
    sa.Column('signed_by', sa.String(), nullable=True),
    sa.Column('npi', sa.String(), nullable=True),
    sa.Column('attestation_statement', sa.String(), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('integrity_hash', sa.String(), nullable=True),
    sa.Column('narrative_edited', sa.Boolean(), nullable=False),
    sa.Column('amendments', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('case_id', 'version')
    )
    op.create_table('slides',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('case_id', GUID(), nullable=False),
    sa.Column('gcs_uri_original', sa.String(), nullable=False),
    sa.Column('gcs_uri_pyramid', sa.String(), nullable=True),
    sa.Column('gcs_uri_pyramid_norm', sa.String(), nullable=True),
    sa.Column('format', sa.String(), nullable=True),
    sa.Column('scanner', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('mpp_x', sa.Float(), nullable=True),
    sa.Column('mpp_y', sa.Float(), nullable=True),
    sa.Column('base_mag', sa.Float(), nullable=True),
    sa.Column('width_px', sa.Integer(), nullable=True),
    sa.Column('height_px', sa.Integer(), nullable=True),
    sa.Column('checksum_sha256', sa.String(), nullable=True),
    sa.Column('label_stripped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stage_executions',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('case_id', GUID(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('input_ref', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('output_ref', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('model_versions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('config_hash', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_edits', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'stage', 'attempt', name='uq_stage_execution_attempt')
    )
    op.create_index('ix_stage_poll', 'stage_executions', ['status', 'stage'], unique=False)

    op.create_table('hotspots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', GUID(), nullable=False),
    sa.Column('stage_execution_id', GUID(), nullable=False),
    sa.Column('polygon_um', sa.JSON(), nullable=False),
    sa.Column('area_mm2', sa.Float(), nullable=True),
    sa.Column('prob_mean', sa.Float(), nullable=True),
    sa.Column('prob_max', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('excluded', sa.Boolean(), nullable=False),
    sa.Column('exclude_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stage_execution_id'], ['stage_executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'case_id')
    )
    op.create_index('ix_hotspots_case_id', 'hotspots', ['case_id'], unique=False)



def downgrade() -> None:
    op.drop_index('ix_hotspots_case_id', table_name='hotspots')
    op.drop_table('hotspots')
    op.drop_index('ix_stage_poll', table_name='stage_executions')
    op.drop_table('stage_executions')
    op.drop_table('slides')
    op.drop_table('reports')
    op.drop_index('ix_hpf_sites_case_id', table_name='hpf_sites')
    op.drop_table('hpf_sites')
    op.drop_table('gradings')
    op.drop_index('ix_detections_case_id', table_name='detections')
    op.drop_table('detections')
    op.drop_table('cases')
    op.drop_table('audit_events')
