/**
 * Central UI Label Dictionary for OncoGemma v6.
 * SPEC-10 and WP-9.3 copy standards:
 * - action.*: <= 3 words, verb first, sentence case
 * - heading.*: <= 4 words, noun phrase, sentence case
 * - help.*: <= 15 words, one sentence
 * - error.*: <= 20 words
 * - No model or vendor names in UI copy (governed by lint-labels.mjs)
 */

export const L = {
  stage: {
    ingest: "Ingest",
    preprocess: "Preprocess",
    qc: "Quality check",
    triage: "Hotspots",
    mitosis: "Mitoses",
    grading: "Grade",
  },
  action: {
    confirm: "Confirm",
    confirmHotspots: "Confirm hotspots",
    confirmMitoses: "Confirm mitoses",
    confirmGrade: "Confirm grade",
    retry: "Retry",
    retryStage: "Retry stage",
    addHotspot: "Add hotspot",
    excludeHotspot: "Exclude",
    includeHotspot: "Restore",
    markMitosis: "Mitosis",
    markNotMitosis: "Not mitosis",
    saveMpp: "Save MPP",
    overrideQc: "Override QC",
    signIn: "Sign in",
    signOut: "Sign out",
    locate: "Show on slide",
    zoomIn: "Zoom in",
    zoomOut: "Zoom out",
    resetView: "Reset view",
    refresh: "Refresh",
    rerunHotspots: "Rerun hotspots",
    replaceHpfs: "Re-place HPFs",
    uploadSlide: "Upload slide",
    cancel: "Cancel",
    close: "Close",
    edit: "Edit",
    save: "Save",
    delete: "Delete",
    viewCase: "View case",
    newCase: "New case",
    addPoint: "Add point",
    finishPolygon: "Finish polygon",
    customPolygon: "Custom polygon",
    boxRoi: "Box ROI",
    recalculate: "Recalculate",
    details: "Details",
    showMarks: "Show marks",
    filterAll: "All",
    filterUnreviewed: "Unreviewed",
    filterConfirmed: "Confirmed",
    filterRejected: "Rejected",
    toggleHeatmap: "Heatmap",
    toggleHotspots: "Hotspots",
    toggleMask: "Mask",
    normColor: "Norm color",
    origColor: "Orig color",
    toggleRois: "Show ROIs",
    rescan: "Rescan",
    saveScore: "Save score",
    invite: "Invite",
    revokeSessions: "Revoke sessions",
    enable: "Enable",
    disable: "Disable",
    mockSignIn: "Mock sign in",
  },
  heading: {
    cases: "Cases",
    research: "Research",
    caseDetails: "Case details",
    workflowPipeline: "Workflow pipeline",
    qualityCheck: "Quality check",
    hotspotTriage: "Hotspot triage",
    mitosisScoring: "Mitosis scoring",
    gradingReview: "Grade review",
    specimenProperties: "Specimen properties",
    hotspots: "Hotspots",
    morphology: "Morphology",
    mitoticCandidates: "Mitotic candidates",
    topHpfs: "Top fields",
    tubuleFormation: "Tubule formation",
    nuclearPleomorphism: "Nuclear pleomorphism",
    mitoticCount: "Mitotic count",
    histologicType: "Histologic type",
    provenance: "Provenance",
    calibration: "Calibration",
    summary: "Summary",
    evidencePatches: "Evidence patches",
    diagnosticConfidence: "Diagnostic confidence",
    hotspotOverview: "Hotspot overview",
    activeHotspots: "Active hotspots",
    proposedRois: "Proposed ROIs",
    polygonVertices: "Polygon points",
    zoomPresets: "Zoom presets",
    patchView: "Patch view",
    nottinghamScore: "Nottingham score",
    nottinghamGrade: "Nottingham grade",
    reviewGates: "Review gates",
    slideOverview: "Slide overview",
    appTitle: "OncoGemma",
    appSubtitle: "Histopathology Copilot",
    appLogo: "OG",
    loginTitle: "Sign In",
    loginSubtitle: "Clinical Review",
    adminUsers: "User management",
    inviteUser: "Invite user",
  },
  help: {
    selectCase: "Select a case to begin review.",
    uploadFirstSlide: "Upload an H&E slide to start.",
    clickToPlaceHotspot: "Click the slide to place a hotspot.",
    reviewAllSamples: "Review each sample; edit if needed.",
    reviewAllCandidates: "Review all candidates to continue.",
    reviewAllHpfs: "Review all HPFs to continue.",
    allCandidatesReviewed: "All candidates reviewed.",
    readyToConfirm: "Ready to confirm.",
    overrideReasonMinLength: "Add a reason with 10 or more characters.",
    inspectMorphology: "Click to inspect microscopic morphology.",
    noHotspots: "No tumor hotspots identified.",
    noMitoses: "No candidate mitotic figures detected.",
    noSlideYet: "No slide yet. Upload one to start.",
    noInvasiveTumor: "No invasive tumor identified.",
    dragDropSlide: "Drag and drop Whole Slide Image files here.",
    enterCustomZoom: "Click to enter custom zoom magnification.",
    editVertices: "Edit polygon boundary points.",
    deletePoint: "Delete selected polygon point.",
    deleteHotspot: "Delete selected tumor hotspot.",
    hotkeyHintMarks: "Press A to toggle marks.",
    hotkeyHintConfirm: "Press Space to confirm.",
    hotkeyHintMitosis: "Press 1 for mitosis, 2 for imposter.",
    confidenceTooltip: "Derived from model agreement and quality checks.",
    hpfSelectionHelp: "Highest mitotic density fields for Nottingham grading.",
    stainNormHelp: "Normalized using Macenko stain decomposition.",
    domainHint: "Sign in with your authorized Google Workspace account.",
    noUsersFound: "No users found in the system.",
  },
  status: {
    running: "Running…",
    awaitingReview: "Ready for review",
    failed: "Failed",
    done: "Done",
    needsHuman: "Needs review",
    pending: "Pending",
    processing: "Processing…",
    confirmed: "Confirmed",
    excluded: "Excluded",
    approved: "Approved",
    rejected: "Rejected",
    grading: "Grading…",
    calibrating: "Calibrating…",
    extractingHotspots: "Extracting hotspots…",
    countingMitoses: "Counting mitoses…",
    analyzingSlide: "Analyzing slide…",
    invited: "Invited",
    active: "Active",
    disabled: "Disabled",
  },
  error: {
    qcFailed: "QC failed. Override with a reason or rescan.",
    noSlideUploaded: "No slide yet. Upload one to start.",
    genericError: "An unexpected error occurred. Please retry or contact support.",
    stageExecutionFailed: "Stage execution failed. Retry the stage or review error details.",
    invalidMpp: "Invalid MPP value. Enter a positive number in micrometers per pixel.",
    uploadFailed: "Slide upload failed. Please verify file format and try again.",
    networkError: "Network connection lost. Please check your connection and retry.",
    unauthorized: "Session expired or unauthorized. Please sign in again.",
    invalidToken: "Authentication token is invalid or expired. Please sign in again.",
    domainNotAllowed: "Your email domain is not authorized to access this system.",
    notProvisioned: "Your account has not been provisioned. Contact an administrator for access.",
    userDisabled: "This account has been disabled. Please contact an administrator.",
    sessionExpired: "Your session has expired. Please sign in again to continue.",
    lastAdmin: "Cannot demote or disable the last remaining administrator.",
    userExists: "A user with this email address already exists.",
    invalidEmail: "Please enter a valid email address.",
    forbidden: "You do not have permission to perform this action.",
    csrfFailed: "Security validation failed. Please refresh the page and try again.",
  },
  field: {
    caseId: "Case ID",
    patientId: "Patient ID",
    slideFile: "Slide file",
    status: "Status",
    stage: "Stage",
    created: "Created",
    mpp: "MPP",
    magnification: "Magnification",
    specimenType: "Specimen type",
    stainQuality: "Stain quality",
    tissueCoverage: "Tissue coverage",
    tumorArea: "Tumor area",
    meanTumorProb: "Mean tumor prob",
    peakTumorProb: "Peak tumor prob",
    confidence: "Confidence",
    density: "Density",
    exclusionReason: "Reason for exclusion",
    overrideReason: "Override reason",
    totalScore: "Total score",
    grade: "Grade",
    mitosisCount: "Mitosis count",
    mitosisScore: "Mitotic score",
    tubuleScore: "Tubule score",
    pleoScore: "Pleomorphism score",
    cellularity: "Cellularity",
    refereeVerdict: "Referee verdict",
    modelVersions: "Model versions",
    configHash: "Config hash",
    runMode: "Run mode",
    scale: "Scale",
    stroma: "Stroma",
    moderate: "Moderate",
    hotspotArea: "Hotspot",
    zoom: "Zoom",
    fieldNumber: "Field",
    xCoord: "X",
    yCoord: "Y",
    pts: "pts",
    reason: "Reason",
    detector: "Det",
    verifier: "Ver",
    manual: "Manual",
    nav: "Nav",
    email: "Email",
    name: "Name",
    role: "Role",
    lastLogin: "Last login",
  },
  unit: {
    um: "µm",
    umPerPx: "µm/px",
    mm2: "mm²",
    mag10x: "10×",
    mag20x: "20×",
    mag40x: "40×",
    percent: "%",
  },
  fmt: {
    mitosesPerArea: (n: number, mm2: number) => `${n} mitoses / ${mm2.toFixed(2)} mm²`,
    hpfScore: (n: number) => `${n} / 10 HPFs`,
    zoomMag: (mag: number) => `${mag}×`,
    totalScoreFmt: (total: number, grade: number) => `Score ${total} (Grade ${grade})`,
    pointsCount: (n: number) => `(${n} pts)`,
    areaMm2: (area: number) => `${area.toFixed(2)} mm²`,
    domainAccount: (domain: string) => `Use your ${domain} Google account`,
  },
} as const;
