/**
 * Central UI Label Dictionary for OncoGemma v6.
 * SPEC-10 and WP-9.3 copy standards:
 * - action.*: <= 3 words, verb first, sentence case
 * - heading.*: <= 4 words, noun phrase, sentence case
 * - help.*: <= 15 words, one sentence
 * - error.*: <= 20 words
 * - No model or vendor names in UI copy (governed by lint-labels.mjs)
 */

export const L = {
  stage: {
    ingest: "Ingest",
    preprocess: "Preprocess",
    qc: "Quality check",
    triage: "Hotspots",
    mitosis: "Mitoses",
    grading: "Grade",
  },
  action: {
    confirm: "Confirm",
    confirmHotspots: "Confirm hotspots",
    confirmMitoses: "Confirm mitoses",
    confirmGrade: "Confirm grade",
    retry: "Retry",
    retryStage: "Retry stage",
    pinHpf: "Pin HPF",
    moveHpf: "Move",
    excludeHotspot: "Exclude",
    includeHotspot: "Restore",
    markMitosis: "Mitosis",
    markNotMitosis: "Not mitosis",
    saveMpp: "Save MPP",
    saveSpecimenType: "Save and continue",
    overrideQc: "Override QC",
    signIn: "Sign in",
    signOut: "Sign out",
    locate: "Show on slide",
    zoomIn: "Zoom in",
    zoomOut: "Zoom out",
    resetView: "Reset view",
    refresh: "Refresh",
    rerunHotspots: "Rerun hotspots",
    replaceHpfs: "Re-place HPFs",
    uploadSlide: "Upload slide",
    cancel: "Cancel",
    close: "Close",
    edit: "Edit",
    save: "Save",
    delete: "Delete",
    viewCase: "View case",
    newCase: "New case",
    recalculate: "Recalculate",
    details: "Details",
    showMarks: "Show marks",
    filterAll: "All",
    filterUnreviewed: "Unreviewed",
    filterConfirmed: "Confirmed",
    filterRejected: "Rejected",
    toggleHeatmap: "Heatmap",
    toggleHotspots: "Hotspots",
    toggleMask: "Mask",
    normColor: "Norm color",
    origColor: "Orig color",
    toggleRois: "Show ROIs",
    rescan: "Rescan",
    saveScore: "Save score",
    invite: "Invite",
    revokeSessions: "Revoke sessions",
    enable: "Enable",
    disable: "Disable",
    mockSignIn: "Mock sign in",
    confirmZeroTumor: "Confirm no tumor",
    override: "Override",
    confirmType: "Confirm type",
    applyOverride: "Apply override",
    viewMitoses: "View mitoses",
    reviewSample: "Review sample",
    clearOverride: "Clear override",
    newBatch: "New batch",
    logIssue: "Log issue",
    compare: "Compare",
    annotate: "Annotate",
    accept: "Accept",
    reject: "Reject",
    exclude: "Exclude",
    retryFailed: "Retry failed",
    cancelBatch: "Cancel batch",
    createIssue: "Create issue",
    updateIssue: "Update issue",
    submitAnnotation: "Submit",
    exportCsv: "Export CSV",
  },
  heading: {
    cases: "Cases",
    research: "Research",
    runs: "Runs",
    newBatch: "New batch",
    action: "Action",
    runDetails: "Run details",
    compareRuns: "Compare runs",
    issueRegister: "Issue register",
    annotationTasks: "Annotation tasks",
    labelQaQueue: "Label QA queue",
    stages: "Stages",
    confusion: "Confusion",
    mitosisCurves: "Mitosis curves",
    slices: "Slices",
    items: "Items",
    errors: "Errors",
    costAndLatency: "Cost and latency",
    batchProgress: "Batch progress",
    decisionTree: "Decision tree",
    caseDetails: "Case details",
    workflowPipeline: "Workflow pipeline",
    qualityCheck: "Quality check",
    hotspotTriage: "Hotspot triage",
    mitosisScoring: "Mitosis scoring",
    gradingReview: "Grade review",
    specimenProperties: "Specimen properties",
    hotspots: "Hotspots",
    morphology: "Morphology",
    mitoticCandidates: "Mitotic candidates",
    topHpfs: "Top fields",
    tubuleFormation: "Tubule formation",
    nuclearPleomorphism: "Nuclear pleomorphism",
    mitoticCount: "Mitotic count",
    histologicType: "Histologic type",
    provenance: "Provenance",
    calibration: "Calibration",
    summary: "Summary",
    evidencePatches: "Evidence patches",
    diagnosticConfidence: "Diagnostic confidence",
    hotspotOverview: "Hotspot overview",
    activeHotspots: "Active hotspots",
    proposedRois: "Proposed ROIs",
    zoomPresets: "Zoom presets",
    patchView: "Patch view",
    nottinghamScore: "Nottingham score",
    nottinghamGrade: "Nottingham grade",
    reviewGates: "Review gates",
    slideOverview: "Slide overview",
    appTitle: "OncoGemma",
    appSubtitle: "Histopathology Copilot",
    appLogo: "OG",
    loginTitle: "Sign In",
    loginSubtitle: "Clinical Review",
    adminUsers: "User management",
    inviteUser: "Invite user",
    mitosisDefinition: "Mitosis definition",
    decisionChain: "Decision chain",
    tubuleSamples: "Tubule samples",
    pleomorphismFields: "Pleomorphism fields",
    mitoticSummary: "Mitotic summary",
    overrideComponent: "Override component",
    caseComplete: "Case complete",
    failuresByClass: "Failures by class",
  },
  help: {
    selectCase: "Select a case to begin review.",
    uploadFirstSlide: "Upload an H&E slide to start.",
    reviewAllSamples: "Review each sample; edit if needed.",
    reviewAllCandidates: "Review all candidates to continue.",
    reviewAllHpfs: "Review all HPFs to continue.",
    allCandidatesReviewed: "All candidates reviewed.",
    readyToConfirm: "Ready to confirm.",
    overrideReasonMinLength: "Add a reason with 10 or more characters.",
    inspectMorphology: "Click to inspect microscopic morphology.",
    noHotspots: "No tumor hotspots identified.",
    noMitoses: "No candidate mitotic figures detected.",
    noSlideYet: "No slide yet. Upload one to start.",
    chooseSpecimenFirst: "Choose the specimen type before uploading.",
    specimenTypeRequired: "State the specimen type to start processing this slide.",
    noInvasiveTumor: "No invasive tumor identified.",
    dragDropSlide: "Drag and drop Whole Slide Image files here.",
    enterCustomZoom: "Click to enter custom zoom magnification.",
    deleteHotspot: "Delete selected tumor hotspot.",
    pinHpfHint: "Click the slide to place an HPF.",
    moveHpfHint: "Click the slide to set the new HPF centre.",
    hotkeyHintMarks: "Press A to toggle marks.",
    hotkeyHintConfirm: "Press Space to confirm.",
    hotkeyHintMitosis: "Press 1 for mitosis, 2 for imposter.",
    confidenceTooltip: "Derived from model agreement and quality checks.",
    hpfSelectionHelp: "Highest mitotic density fields for Nottingham grading.",
    stainNormHelp: "Normalized using Macenko stain decomposition.",
    domainHint: "Sign in with your authorized Google Workspace account.",
    noUsersFound: "No users found in the system.",
    hotspotsLimited: "Hotspot coverage was limited by available tissue area.",
    noInvasiveDetected: "No invasive tumor detected across evaluated slide regions.",
    hpfCountWarning: "Fewer than 10 standardized high-power fields evaluated.",
    equivocalReviewNotice: "Review equivocal candidates before proceeding.",
    nearGradeBoundary: "Sum is near a grade boundary; check components.",
    needsHumanGrading: "Some components require review before confirmation.",
    insufficientNuclei: "Fewer than 200 nuclei found across evaluated fields.",
    gradingConfirmed: "Grading is confirmed and case is complete.",
    reasonMinChars: "Reason must be at least 10 characters.",
    valWhatIfHelp: "Val what-if threshold sweep; not saved as result.",
    blindAnnotationNotice: "Blinded annotation mode active; model outputs hidden.",
    resolutionRequiresRunHelp: "Resolving requires a qualifying validation run reference.",
    categoryRemedyHelp: "Guidance on remedy class for category.",
    manifestUriHelp: "Upload backend/eval/manifests/tcga_brca_idc_val.parquet to GCS, then enter its gs:// URI.",
    runThroughHelp: "Runs start at ingest and stop for review after the chosen stage.",
    testAccessHelp: "Test split access is audited. State why this run needs it.",
  },
  status: {
    running: "Running…",
    awaitingReview: "Ready for review",
    failed: "Failed",
    done: "Done",
    needsHuman: "Needs review",
    pending: "Pending",
    processing: "Processing…",
    confirmed: "Confirmed",
    excluded: "Excluded",
    approved: "Approved",
    rejected: "Rejected",
    grading: "Grading…",
    calibrating: "Calibrating…",
    extractingHotspots: "Extracting hotspots…",
    countingMitoses: "Counting mitoses…",
    analyzingSlide: "Analyzing slide…",
    invited: "Invited",
    active: "Active",
    disabled: "Disabled",
    cancelled: "Cancelled",
  },
  error: {
    qcFailed: "QC failed. Override with a reason or rescan.",
    noSlideUploaded: "No slide yet. Upload one to start.",
    genericError: "An unexpected error occurred. Please retry or contact support.",
    stageExecutionFailed: "Stage execution failed. Retry the stage or review error details.",
    invalidMpp: "Invalid MPP value. Enter a positive number in micrometers per pixel.",
    uploadFailed: "Slide upload failed. Please verify file format and try again.",
    networkError: "Network connection lost. Please check your connection and retry.",
    unauthorized: "Session expired or unauthorized. Please sign in again.",
    invalidToken: "Authentication token is invalid or expired. Please sign in again.",
    domainNotAllowed: "Your email domain is not authorized to access this system.",
    notProvisioned: "Your account has not been provisioned. Contact an administrator for access.",
    userDisabled: "This account has been disabled. Please contact an administrator.",
    sessionExpired: "Your session has expired. Please sign in again to continue.",
    lastAdmin: "Cannot demote or disable the last remaining administrator.",
    userExists: "A user with this email address already exists.",
    invalidEmail: "Please enter a valid email address.",
    forbidden: "You do not have permission to perform this action.",
    csrfFailed: "Security validation failed. Please refresh the page and try again.",
    invalidSite: "The HPF circle must lie inside the slide.",
    triageRerunRequired: "This case was triaged before HPF sites were introduced. Re-run hotspot detection.",
    equivocalUnreviewed: "All equivocal candidates inside fields must be reviewed before confirmation.",
    histotypeUnconfirmed: "Confirm the histologic type before confirming Nottingham grade.",
    missingComponent: "All Nottingham components must be evaluated before confirming grade.",
    notAwaitingReview: "Stage is not awaiting review.",
    reasonTooShort: "Reason must contain at least 10 characters.",
    resolutionRequiresRun: "Resolving an issue requires specifying a validating run demonstrating metric improvement.",
    reasonRequired: "A reason is required when editing or excluding label QA items.",
    manifestMismatch: "Runs must have matching manifest hashes to be compared.",
    manifestUriInvalid: "Manifest URI must start with gs://.",
    testAccessReasonRequired: "Test split runs require a reason for the audit log.",
  },
  field: {
    caseId: "Case ID",
    patientId: "Patient ID",
    slideFile: "Slide file",
    status: "Status",
    stage: "Stage",
    created: "Created",
    mpp: "MPP",
    magnification: "Magnification",
    specimenType: "Specimen type",
    specimenResection: "Resection",
    specimenCoreBiopsy: "Core biopsy",
    specimenUnknown: "Not stated",
    stainQuality: "Stain quality",
    tissueCoverage: "Tissue coverage",
    tumorArea: "Tumor area",
    meanTumorProb: "Mean tumor prob",
    peakTumorProb: "Peak tumor prob",
    confidence: "Confidence",
    density: "Density",
    exclusionReason: "Reason for exclusion",
    overrideReason: "Override reason",
    totalScore: "Total score",
    grade: "Grade",
    mitosisCount: "Mitosis count",
    mitosisScore: "Mitotic score",
    tubuleScore: "Tubule score",
    pleoScore: "Pleomorphism score",
    cellularity: "Cellularity",
    refereeVerdict: "Referee verdict",
    modelVersions: "Model versions",
    configHash: "Config hash",
    runMode: "Run mode",
    scale: "Scale",
    stroma: "Stroma",
    moderate: "Moderate",
    hotspotArea: "Hotspot",
    zoom: "Zoom",
    fieldNumber: "Field",
    xCoord: "X",
    yCoord: "Y",
    pts: "pts",
    tumorEdge: "Tumour edge",
    reason: "Reason",
    detector: "Det",
    verifier: "Ver",
    manual: "Manual",
    nav: "Nav",
    email: "Email",
    name: "Name",
    role: "Role",
    action: "Action",
    lastLogin: "Last login",
    scoreKind: "Score type",
    tumorFraction: "Tumor fraction",
    expectedMitoses: "Expected mitoses",
    hotspotRank: "Rank",
    prescanExpectedCount: "Expected count",
    prescanThenTumor: "Prescan and tumor",
    opacity: "Opacity",
    detectorProb: "Detector p_a",
    classifierProb: "Classifier p_b",
    vlmVerdict: "VLM verdict",
    ruleOverride: "Rule override",
    counted: "Counted",
    equivocal: "Equivocal",
    membraneAbsent: "Membrane absent",
    condensedProjections: "Condensed projections",
    phase: "Phase",
    neoplasticCell: "Neoplastic cell",
    mimic: "Mimic",
    decisionPath: "Path",
    tumorGate: "Tumor gate",
    tumorGateNotApplied: "Not applied",
    inTumor: "In tumor",
    outsideTumor: "Outside tumor",
    hpfLabel: "HPF",
    noMitoticScore: "No score (no HPFs)",
    hotkey: "Hotkey",
    definition: "Definition",
    tubulePercent: "Tubules",
    tumorPresent: "Tumor present",
    nucleiCount: "Nuclei count",
    medianArea: "Median area",
    areaCv: "Area CV",
    estimator: "Estimator",
    aggregation: "Aggregation",
    proposedType: "Proposed type",
    rationale: "Rationale",
    samplesUsed: "Samples used",
    component: "Component",
    overridden: "Overridden",
    nearBoundary: "Near boundary",
    runName: "Run name",
    dataset: "Dataset",
    split: "Split",
    arm: "Arm",
    gate: "Gate",
    disjoint: "Disjoint",
    intProv: "INT-PROV",
    intFall: "INT-FALL",
    lockedTest: "Locked test",
    headlineMetrics: "Headline metrics",
    operatingPoint: "Operating point",
    ece: "ECE",
    costUsd: "Cost USD",
    latencyMs: "Latency ms",
    severity: "Severity",
    category: "Category",
    evidence: "Evidence",
    resolvedIn: "Resolved in",
    resolutionNote: "Resolution note",
    groundTruth: "Ground truth",
    prediction: "Prediction",
    sumError: "Sum error",
    licenseScope: "License scope",
    delta: "Delta",
    deltaLow: "Delta low",
    deltaHigh: "Delta high",
    mcnemarP: "McNemar p",
    manifestUri: "Manifest URI",
    manifestUriPlaceholder: "gs://<bucket>/manifests/tcga_brca_idc_val.parquet",
    concurrency: "Concurrency",
    testAccessReason: "Test access reason",
    splitTrain: "Train",
    splitVal: "Validation",
    splitTest: "Test",
    modeAuto: "Auto",
    modeManual: "Manual",
  },
  unit: {
    um: "µm",
    um2: "µm²",
    umPerPx: "µm/px",
    mm2: "mm²",
    mag10x: "10×",
    mag20x: "20×",
    mag40x: "40×",
    percent: "%",
  },
  fmt: {
    mitosesPerArea: (n: number, mm2: number) => `${n} mitoses / ${mm2.toFixed(2)} mm²`,
    hpfScore: (n: number) => `${n} / 10 HPFs`,
    zoomMag: (mag: number) => `${mag}×`,
    totalScoreFmt: (total: number, grade: number) => `Score ${total} (Grade ${grade})`,
    hpfSitesActive: (active: number, target: number) => `HPF sites: ${active} / ${target}`,
    hotspotOverlap: (ids: string[]) =>
      `HPF circles cannot overlap. Pin the new HPF further from HPF ${ids.join(", ")}.`,
    tooManySites: (target: number) => `${target} HPFs are already active. Exclude one before pinning another.`,
    tissueInadequateBanner: (nAvailable: number, target: number) =>
      `Tissue inadequate: only ${nAvailable} of ${target} HPFs (0.5 mm circles with enough tumour) fit on this slide. The mitotic score will be based on fewer HPFs.`,
    tissueInadequateAck: (target: number) => `Tissue is inadequate for ${target} HPFs`,
    areaMm2: (area: number) => `${area.toFixed(2)} mm²`,
    domainAccount: (domain: string) => `Use your ${domain} Google account`,
    summaryMitosis: (count: number, mm2: number, score: number | null) =>
      score === null
        ? `${count} mitoses / ${mm2.toFixed(2)} mm² · No score (no HPFs)`
        : `${count} mitoses / ${mm2.toFixed(2)} mm² · Score ${score}`,
    percent: (fraction: number) => `${Math.round(fraction * 100)}%`,
  },
} as const;
