steps:
  # 1. Build Worker Container Image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/oncogemma-repo/worker:latest'
      - '-f'
      - 'ops/docker/Dockerfile.worker'
      - '.'
    id: 'build-worker'

  # 2. Push Container Image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '$_REGION-docker.pkg.dev/$PROJECT_ID/oncogemma-repo/worker:latest']
    id: 'push-worker'

  # 3. Update Worker Cloud Run Job
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'jobs'
      - 'update'
      - 'oncogemma-worker-job'
      - '--image=$_REGION-docker.pkg.dev/$PROJECT_ID/oncogemma-repo/worker:latest'
      - '--region=$_REGION'
      - '--add-cloudsql-instances=$PROJECT_ID:$_REGION:oncogemma-dev-psql'
      - '--update-env-vars=VERTEX_MITOSIS_ENDPOINT_ID=6276949705008087040,VERTEX_MITOSIS_LOCATION=us-central1,USE_GEMINI_FLASH_REFEREE=true,GEMINI_REFEREE_MODEL=gemini-2.5-flash,CLOUD_SQL_CONNECTION_NAME=$PROJECT_ID:$_REGION:oncogemma-dev-psql'
      - '--set-secrets=DB_PASSWORD=og-db-password:latest'
    id: 'update-worker-job'


substitutions:
  _REGION: 'us-central1'

options:
  logging: CLOUD_LOGGING_ONLY
